### ISSUE TITLE
_curses.error: init_pair() returned ERR

### ISSUE THREAD

**Issue by chzchzchz** [mikedesu/asciishade#1]
Greetings developer! Avid ascii artist Chzz Chatman here. I attempted running asciishade inside my gentoo terminal but got this error:
```
Traceback (most recent call last):
  File "main.py", line 160, in <module>
    wrapper(main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "main.py", line 148, in main
    define_color_pairs()
  File "main.py", line 124, in define_color_pairs
    init_pair(x, i, j)
_curses.error: init_pair() returned ERR
```
Both uxterm and xterm return the same backtrace. I tried reaching out on the Eris Free Network (efnet) but I appear banned from the recommended support channel `#evildojo`. Possibly a clerical error and/or misconfiguration. Which terminal is suggested for the best asciishade experience?

Yours in Christ,
Chzz C. Chatman

**Comment by AndroidKitKat** [comment]
I'm having the same issue with my M1 Max MacBook Pro running macOS 12.3.1.

```
$ python3 main.py 
Traceback (most recent call last):
  File "/Users/me/Developer/asciishade/main.py", line 160, in <module>
    wrapper(main)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/me/Developer/asciishade/main.py", line 148, in main
    define_color_pairs()
  File "/Users/me/Developer/asciishade/main.py", line 124, in define_color_pairs
    init_pair(x, i, j)
_curses.error: init_pair() returned ERR
```

Thank you and God Bless.

**Comment by venatiodecorus** [comment]
Same error here on macOS w/ python 3.9.12

**Comment by AndroidKitKat** [comment]
> I'm having the same issue with my M1 Max MacBook Pro running macOS 12.3.1.
> 
> ```
> $ python3 main.py 
> Traceback (most recent call last):
>   File "/Users/me/Developer/asciishade/main.py", line 160, in <module>
>     wrapper(main)
>   File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
>     return func(stdscr, *args, **kwds)
>   File "/Users/me/Developer/asciishade/main.py", line 148, in main
>     define_color_pairs()
>   File "/Users/me/Developer/asciishade/main.py", line 124, in define_color_pairs
>     init_pair(x, i, j)
> _curses.error: init_pair() returned ERR
> ```
> 
> Thank you and God Bless.

I am also running this in the Apple terminal just for another piece of potentially useful information

**Comment by AndroidKitKat** [comment]
> > I'm having the same issue with my M1 Max MacBook Pro running macOS 12.3.1.
> > ```
> > $ python3 main.py 
> > Traceback (most recent call last):
> >   File "/Users/me/Developer/asciishade/main.py", line 160, in <module>
> >     wrapper(main)
> >   File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
> >     return func(stdscr, *args, **kwds)
> >   File "/Users/me/Developer/asciishade/main.py", line 148, in main
> >     define_color_pairs()
> >   File "/Users/me/Developer/asciishade/main.py", line 124, in define_color_pairs
> >     init_pair(x, i, j)
> > _curses.error: init_pair() returned ERR
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you and God Bless.
> 
> I am also running this in the Apple terminal just for another piece of potentially useful information

I also just tested this in my Mac OS X 10.9.1 Mavericks on my 2009 21 inch iMac and am receiving the same error

**Comment by AndroidKitKat** [comment]
> > > I'm having the same issue with my M1 Max MacBook Pro running macOS 12.3.1.
> > > ```
> > > $ python3 main.py 
> > > Traceback (most recent call last):
> > >   File "/Users/me/Developer/asciishade/main.py", line 160, in <module>
> > >     wrapper(main)
> > >   File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
> > >     return func(stdscr, *args, **kwds)
> > >   File "/Users/me/Developer/asciishade/main.py", line 148, in main
> > >     define_color_pairs()
> > >   File "/Users/me/Developer/asciishade/main.py", line 124, in define_color_pairs
> > >     init_pair(x, i, j)
> > > _curses.error: init_pair() returned ERR
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Thank you and God Bless.
> > 
> > 
> > I am also running this in the Apple terminal just for another piece of potentially useful information
> 
> I also just tested this in my Mac OS X 10.9.1 Mavericks on my 2009 21 inch iMac and am receiving the same error

The one in Mavericks was also using the Apple Terminal

**Comment by mikedesu** [comment]
Everyone running `asciishade` in xterm or apple terminal:

Before doing `python3 main.py`, do: `export TERM='xterm-256color`

[![asciicast](https://asciinema.org/a/SsNnL2eCqS5e8QJiXDaJgfP1S.svg)](https://asciinema.org/a/SsNnL2eCqS5e8QJiXDaJgfP1S)

Thank you all for the feedback. 

I will be closing this issue now.

I've tested it in xterm, and it should also work on apple terminal, but if there is still a problem, please open a new issue. 

God bless

**Comment by venatiodecorus** [comment]
```
➜  asciishade git:(main) echo $TERM
xterm-256color
➜  asciishade git:(main) python3 main.py
Traceback (most recent call last):
  File "/Users/venatio/dev/asciishade/main.py", line 160, in <module>
    wrapper(main)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/venatio/dev/asciishade/main.py", line 148, in main
    define_color_pairs()
  File "/Users/venatio/dev/asciishade/main.py", line 124, in define_color_pairs
    init_pair(x, i, j)
_curses.error: init_pair() returned ERR
```
