### ISSUE TITLE
Is asciishade dead?

### ISSUE THREAD

**Issue by hughbord** [mikedesu/asciishade#10]
Yup. Looks like it is. Face it darkmage, you cannot complete with my superior intellect, coding ability and autism. I also outrank you on looks and personality, as evident from my superior Patreon list and supporters.

It's been what 10 days you aint pushed any updates. Your pathetic editor doesn't even support backticks, let alone exporting to IRC. Hahaha oh god I have to wipe the tears from my eyes while reading your code. It hurts that much I gotta wash my eyes out with bleach just to make it stop.

For example I know a few people who have used asciishade and afterwards suffered from health implications, such as heart attacks, diarrhea and sudden death. Is this intentional? I think so, given you have been known to worship Satan and do black magic.

I hope you are prepared for my psychological warfare onslaught as retaliation for even attempting to create a rival ASCII editor. Even right now your weak and feeble mind is collapsing upon reading my github issue. The issue is you, Mike Bell. Your grandma wont save you from my vicious attacks.

Haha nah ol Mike, my friend. Just trolling, you know me. I have a reputation for internet trolling as you can imagine. Good to see you got around to this and great to see some more ASCII art editors in the world. Let me know if you need any coding help, maybe I can do some PRs? Could I go live on your stream?

**Comment by mikedesu** [comment]
I laughed irl. Hope you are well bird.
