### ISSUE TITLE
_curses.error: addwstr() returned ERR

### ISSUE THREAD

**Issue by chzchzchz** [mikedesu/asciishade#3]
Hello developer! ASCII artist Chzz Chatman again. I ran `TERM=xterm-256color python3 ./main.py` per the guidance and I was grateful to finally be greeted by the `asciishade` editor main screen. However, I then reduced the window height by moving its tile to a different position in my Tiling Window Manager and the `asciishade` application instantly terminated with the following backtrace:
```
Traceback (most recent call last): TERM=xterm-256color python3 ./main.py 
  File "./main.py", line 160, in <module>
    wrapper(main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "./main.py", line 153, in main
    draw_hud(s)
  File "./main.py", line 54, in draw_hud
    s.addstr(max_y-1, 0, f'x: {x:3} | ', color_pair(hud_color)) 
_curses.error: addwstr() returned ERR
```
Any ideas how to move forward? I am using xterm on gentoo Linux with Python 3.8.12 and i3 Window Manager, if that matters.

**Comment by venatiodecorus** [comment]
same issue on debian, crashes on resize

**Comment by mikedesu** [comment]
At present, the recommended way to run `asciishade` is to first decide your terminal size, and then run `python3 main.py`. Resizing of the terminal / canvas will be handled in a future release, sometime after saving/loading. Thanks for bringing this up. Closing this issue for now.
