### ISSUE TITLE
memory data writing to screen?

### ISSUE THREAD

**Issue by venatiodecorus** [mikedesu/asciishade#5]
pressing 'I' seems to write some sort of memory dump to the screen. not sure if this is a bug or undocumented feature? 

![image](https://user-images.githubusercontent.com/1077677/166344674-faf91962-76e1-4d4b-96d9-721402d9aff8.png)

**Comment by mikedesu** [comment]
Ah yes. Early version of "get character and attributes under cursor". Forgot to add in the README. Thx
