### ISSUE TITLE
narrow asciis crash on start

### ISSUE THREAD

**Issue by chzchzchz** [mikedesu/asciishade#8]
Greetings developer! Chzz Chatman, aspiring `asciishade` artist here; still trying to master this software application. I followed the [latest guidance](https://github.com/mikedesu/asciishade/issues/3) for running `asciishade` by selecting a fixed terminal size prior to composing an ascii. For my use case, I wish to make a very narrow ascii so I set my terminal to 13 columns (total number of colonies in the United States immediately prior to independence). However, when I try to start `asciishade` the program exits back to the command prompt after dumping the following backtrace:

```
Traceback (most recent call last):  File "main.py", line 160, in <module>
    wrapper(main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "main.py", line 153, in main
    draw_hud(s)
  File "main.py", line 56, in draw_hud
    s.addstr(f'{current_color_pair:3}', color_pair(hud_color))
_curses.error: addwstr() returned ERR
```

Seems like I'm having rotten luck today. I hope I won't need a new computer to create ascii art in my terminal. Any ideas?

**Comment by mikedesu** [comment]
Setting the window size to that few columns will currently break the hud display. I recommend using a more reasonable terminal size like 80x20. Currently it looks like column size of 18 will break the display. I will add error checking and informative messages to let the user know to run the terminal in a recommended width/height if the program detects they are using a small terminal. 

Appreciate the feedback. Closing as I am aware of the issue.
